version: "3.9"
services:
  rabbitmq:
      image: rabbitmq:management
      container_name: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      networks:
        - user-net
      restart: always
  mysqlservice:
      image: mysql:latest
      ports:
        - "3306:3306"
      container_name: mysqlservice
      networks:
        - user-net
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USERNAME: root
        MYSQL_PASSWORD: root
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_DATABASE: user


  mongo-service:
    image: mongo:latest
    container_name: bankmongo-container
    networks:
      - user-net
    ports:
      - "27017:27017"

  bank-service:
    container_name: bank-service-Container
    build: BankServiceDemo/
    networks:
      - user-net
    ports:
      - "8093:8093"
    depends_on:
      - mongo-service
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq

    restart: always

  usermanagement:
      container_name: user-management-container
      build: UserManagementService/
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysqlservice:3306/user
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
        SPRING_RABBITMQ_HOST: rabbitmq
      networks:
        - user-net
      ports:
        - "8085:8085"
      depends_on:
        - mysqlservice
      restart: always



networks:
  user-net:
    driver: bridge